version: '3'

services:
  db:
    image: postgres:9.6
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=wbooks-api
      - POSTGRES_PASSWORD=wbooks-api

  redis:
    image: redis:4.0.11

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    environment:
      - DB_HOST=db
      - REDIS_URL=redis://redis:6379/

  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - redis
      - db
    links:
      - db
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/
      - DB_HOST=db
